add a dependent library to the artifact instead of a single binary

diff --git a/.github/workflows/release-build.yml b/.github/workflows/release-build.yml
--- a/.github/workflows/release-build.yml
+++ b/.github/workflows/release-build.yml
@@ -18,8 +18,8 @@ jobs:
     - name: "Create compressed repository source"
       run: |
         git archive --format=tar --prefix "lbm-${{ env.VERSION }}/" HEAD | gzip -9n > lbm-${{ env.VERSION }}.tgz
-        md5sum lbm-${{ env.VERSION }}.tgz | awk '{print $1}' > lbm-${{ env.VERSION }}.tgz.md5
-        sha256sum lbm-${{ env.VERSION }}.tgz | awk '{print $1}' > lbm-${{ env.VERSION }}.tgz.sha256
+        md5sum lbm-${{ env.VERSION }}.tgz > lbm-${{ env.VERSION }}.tgz.md5
+        sha256sum lbm-${{ env.VERSION }}.tgz > lbm-${{ env.VERSION }}.tgz.sha256
     - name: "Store compressed source"
       uses: actions/upload-artifact@v3
       with:
@@ -28,11 +28,6 @@ jobs:
           lbm-${{ env.VERSION }}.tgz
           lbm-${{ env.VERSION }}.tgz.md5
           lbm-${{ env.VERSION }}.tgz.sha256
-    - name: "Upload compressed repository source (to share other jobs)"
-      uses: actions/upload-artifact@v3
-      with:
-        path: lbm-${{ env.VERSION }}.tgz
-        name: lbm-${{ env.VERSION }}.tgz
 
   build_for_linux:
     name: "Release Build for Linux"
@@ -45,9 +40,13 @@ jobs:
           - arch: amd64
             cc: x86_64-linux-gnu-gcc
             cxx: x86_64-linux-gnu-g++
+            libwasmvm: libwasmvm.x86_64.so
+            test: 1
           - arch: arm64
             cc: aarch64-linux-gnu-gcc
             cxx: aarch64-linux-gnu-g++
+            libwasmvm: libwasmvm.aarch64.so
+            test: 0
     steps:
       - name: "Set tag as version"
         run: echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV  # set env.VERSION=v0.0.0
@@ -55,7 +54,7 @@ jobs:
         run: |
           sudo apt update
           sudo apt upgrade -y
-          sudo apt install -y build-essential g++-x86-64-linux-gnu g++-aarch64-linux-gnu
+          sudo apt install -y build-essential g++-x86-64-linux-gnu g++-aarch64-linux-gnu wget
       - name: "Install go"
         uses: actions/setup-go@v3
         with:
@@ -75,17 +74,28 @@ jobs:
       - name: "Build artifact: linux-${{ matrix.arch }}"
         run: |
           make clean build GOARCH=${{ matrix.arch }} CC=${{ matrix.cc }} CXX=${{ matrix.cxx }}
-          mv ./build/lbm ./build/lbm-${{ env.ID }}
-          md5sum ./build/lbm-${{ env.ID }} | awk '{print $1}' > ./build/lbm-${{ env.ID }}.md5
-          sha256sum ./build/lbm-${{ env.ID }} | awk '{print $1}' > ./build/lbm-${{ env.ID }}.sha256
+      - name: "Archive artifact: linux-${{ matrix.arch }}"
+        run: |
+          mkdir -p ./artifacts/lbm-${{ env.ID }}
+          mv ./build/lbm ./artifacts/lbm-${{ env.ID }}/lbm-${{ env.ID }}
+          cd ./artifacts
+          LIBWASMVM=`find ~ -name ${{ matrix.libwasmvm }} -type f`
+          if [ ! -f "$LIBWASMVM" ]; then echo "ERROR: ${{ matrix.libwasmvm }} not found: $LIBWASMVM"; exit 1; fi
+          cp "$LIBWASMVM" ./lbm-${{ env.ID }}/${{ matrix.libwasmvm }}
+          ls -laF ./lbm-${{ env.ID }}
+          echo "MD5: `md5sum ./lbm-${{ env.ID }}/lbm-${{ env.ID }}`"
+          if [ ${{ matrix.test }} -eq 1 ]; then echo "Binary launch version: `LD_LIBRARY_PATH=./lbm-${{ env.ID }} ./lbm-${{ env.ID }}/lbm-${{ env.ID }} version`" 2>&1; fi
+          tar zcvf ./lbm-${{ env.ID }}.tgz lbm-${{ env.ID }}/
+          md5sum lbm-${{ env.ID }}.tgz > ./lbm-${{ env.ID }}.md5
+          sha256sum lbm-${{ env.ID }}.tgz > ./lbm-${{ env.ID }}.sha256
       - name: "Store artifact: linux-${{ matrix.arch }}"
         uses: actions/upload-artifact@v3
         with:
           name: release-${{ env.VERSION }}
           path: |
-            ./build/lbm-${{ env.ID }}
-            ./build/lbm-${{ env.ID }}.md5
-            ./build/lbm-${{ env.ID }}.sha256
+            ./artifacts/lbm-${{ env.ID }}.tgz
+            ./artifacts/lbm-${{ env.ID }}.md5
+            ./artifacts/lbm-${{ env.ID }}.sha256
 
   build_for_darwin:
     name: "Release Build for macOS"
@@ -94,6 +104,13 @@ jobs:
     strategy:
       matrix:
         arch: [ "amd64", "arm64" ]
+        include:
+          - arch: amd64
+            libwasmvm: libwasmvm.dylib
+            test: 1
+          - arch: arm64
+            libwasmvm: libwasmvm.dylib
+            test: 0
     steps:
     - name: "Set tag as version"
       run: echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV  # set env.VERSION=v0.0.0
@@ -122,17 +139,28 @@ jobs:
     - name: "Build artifact: darwin-${{ matrix.arch }}"
       run: |
         make clean build GOARCH=${{ matrix.arch }}
-        mv ./build/lbm ./build/lbm-${{ env.ID }}
-        md5sum ./build/lbm-${{ env.ID }} | awk '{print $1}' > ./build/lbm-${{ env.ID }}.md5
-        shasum -a 256 ./build/lbm-${{ env.ID }} | awk '{print $1}' > ./build/lbm-${{ env.ID }}.sha256
+    - name: "Archive artifact: darwin-${{ matrix.arch }}"
+      run: |
+        mkdir -p ./artifacts/lbm-${{ env.ID }}
+        mv ./build/lbm ./artifacts/lbm-${{ env.ID }}/lbm-${{ env.ID }}
+        cd ./artifacts
+        LIBWASMVM=`find ~ -name ${{ matrix.libwasmvm }} -type f`
+        if [ ! -f "$LIBWASMVM" ]; then echo "ERROR: ${{ matrix.libwasmvm }} not found: $LIBWASMVM"; exit 1; fi
+        cp "$LIBWASMVM" ./lbm-${{ env.ID }}/${{ matrix.libwasmvm }}
+        ls -laF ./lbm-${{ env.ID }}
+        echo "MD5: `md5sum ./lbm-${{ env.ID }}/lbm-${{ env.ID }}`"
+        if [ ${{ matrix.test }} -eq 1 ]; then echo "Binary launch version: `LD_LIBRARY_PATH=./lbm-${{ env.ID }} ./lbm-${{ env.ID }}/lbm-${{ env.ID }} version`" 2>&1; fi
+        tar zcvf ./lbm-${{ env.ID }}.tgz lbm-${{ env.ID }}/
+        md5sum lbm-${{ env.ID }}.tgz > ./lbm-${{ env.ID }}.md5
+        shasum -a 256 lbm-${{ env.ID }}.tgz > ./lbm-${{ env.ID }}.sha256
     - name: "Store artifact: darwin-${{ matrix.arch }}"
       uses: actions/upload-artifact@v3
       with:
         name: release-${{ env.VERSION }}
         path: |
-          ./build/lbm-${{ env.ID }}
-          ./build/lbm-${{ env.ID }}.md5
-          ./build/lbm-${{ env.ID }}.sha256
+          ./artifacts/lbm-${{ env.ID }}.tgz
+          ./artifacts/lbm-${{ env.ID }}.md5
+          ./artifacts/lbm-${{ env.ID }}.sha256
 
   create_release:
     name: "Create Release"
@@ -156,17 +184,17 @@ jobs:
         echo "Version: ${{ env.VERSION }}" >> build_report.txt
         echo "Commit: ${{ github.sha }}" >> build_report.txt
         echo "Checksums MD5:" >> build_report.txt
-        echo " `cat lbm-${{ env.VERSION }}-linux-amd64.md5` lbm-${{ env.VERSION }}-linux-amd64" >> build_report.txt
-        echo " `cat lbm-${{ env.VERSION }}-linux-arm64.md5` lbm-${{ env.VERSION }}-linux-arm64"  >> build_report.txt
-        echo " `cat lbm-${{ env.VERSION }}-darwin-amd64.md5` lbm-${{ env.VERSION }}-darwin-amd64" >> build_report.txt
-        echo " `cat lbm-${{ env.VERSION }}-darwin-arm64.md5` lbm-${{ env.VERSION }}-darwin-arm64" >> build_report.txt
-        echo " `cat lbm-${{ env.VERSION }}.tgz.md5` lbm-${{ env.VERSION }}.tgz" >> build_report.txt
+        echo "  `cat lbm-${{ env.VERSION }}-linux-amd64.md5`" >> build_report.txt
+        echo "  `cat lbm-${{ env.VERSION }}-linux-arm64.md5`" >> build_report.txt
+        echo "  `cat lbm-${{ env.VERSION }}-darwin-amd64.md5`" >> build_report.txt
+        echo "  `cat lbm-${{ env.VERSION }}-darwin-arm64.md5`" >> build_report.txt
+        echo "  `cat lbm-${{ env.VERSION }}.tgz.md5`" >> build_report.txt
         echo "Checksums SHA256:" >> build_report.txt
-        echo " `cat lbm-${{ env.VERSION }}-linux-amd64.sha256` lbm-${{ env.VERSION }}-linux-amd64" >> build_report.txt
-        echo " `cat lbm-${{ env.VERSION }}-linux-arm64.sha256` lbm-${{ env.VERSION }}-linux-arm64" >> build_report.txt
-        echo " `cat lbm-${{ env.VERSION }}-darwin-amd64.sha256` lbm-${{ env.VERSION }}-darwin-amd64" >> build_report.txt
-        echo " `cat lbm-${{ env.VERSION }}-darwin-arm64.sha256` lbm-${{ env.VERSION }}-darwin-arm64" >> build_report.txt
-        echo " `cat lbm-${{ env.VERSION }}.tgz.sha256` lbm-${{ env.VERSION }}.tgz" >> build_report.txt
+        echo "  `cat lbm-${{ env.VERSION }}-linux-amd64.sha256`" >> build_report.txt
+        echo "  `cat lbm-${{ env.VERSION }}-linux-arm64.sha256`" >> build_report.txt
+        echo "  `cat lbm-${{ env.VERSION }}-darwin-amd64.sha256`" >> build_report.txt
+        echo "  `cat lbm-${{ env.VERSION }}-darwin-arm64.sha256`" >> build_report.txt
+        echo "  `cat lbm-${{ env.VERSION }}.tgz.sha256`" >> build_report.txt
     - name: "Create release note"
       run: |
         cat ./RELEASE_NOTE.md > release_note.txt
@@ -192,8 +220,8 @@ jobs:
         GITHUB_TOKEN: ${{ github.token }}
       with:
         upload_url: ${{ steps.create_release.outputs.upload_url }}
-        asset_path: lbm-${{ env.VERSION }}-linux-amd64
-        asset_name: lbm-${{ env.VERSION }}-linux-amd64
+        asset_path: lbm-${{ env.VERSION }}-linux-amd64.tgz
+        asset_name: lbm-${{ env.VERSION }}-linux-amd64.tgz
         asset_content_type: application/octet-stream
     - name: "Upload artifact: lbm-${{ env.VERSION }}-linux-arm64"
       uses: actions/upload-release-asset@v1
@@ -201,8 +229,8 @@ jobs:
         GITHUB_TOKEN: ${{ github.token }}
       with:
         upload_url: ${{ steps.create_release.outputs.upload_url }}
-        asset_path: lbm-${{ env.VERSION }}-linux-arm64
-        asset_name: lbm-${{ env.VERSION }}-linux-arm64
+        asset_path: lbm-${{ env.VERSION }}-linux-arm64.tgz
+        asset_name: lbm-${{ env.VERSION }}-linux-arm64.tgz
         asset_content_type: application/octet-stream
     - name: "Upload artifact: lbm-${{ env.VERSION }}-dawrin-amd64"
       uses: actions/upload-release-asset@v1
@@ -210,8 +238,8 @@ jobs:
         GITHUB_TOKEN: ${{ github.token }}
       with:
         upload_url: ${{ steps.create_release.outputs.upload_url }}
-        asset_path: lbm-${{ env.VERSION }}-darwin-amd64
-        asset_name: lbm-${{ env.VERSION }}-darwin-amd64
+        asset_path: lbm-${{ env.VERSION }}-darwin-amd64.tgz
+        asset_name: lbm-${{ env.VERSION }}-darwin-amd64.tgz
         asset_content_type: application/octet-stream
     - name: "Upload artifact: lbm-${{ env.VERSION }}-dawrin-arm64"
       uses: actions/upload-release-asset@v1
@@ -219,8 +247,8 @@ jobs:
         GITHUB_TOKEN: ${{ github.token }}
       with:
         upload_url: ${{ steps.create_release.outputs.upload_url }}
-        asset_path: lbm-${{ env.VERSION }}-darwin-arm64
-        asset_name: lbm-${{ env.VERSION }}-darwin-arm64
+        asset_path: lbm-${{ env.VERSION }}-darwin-arm64.tgz
+        asset_name: lbm-${{ env.VERSION }}-darwin-arm64.tgz
         asset_content_type: application/octet-stream
     - name: "Upload artifact: compressed repository source"
       uses: actions/upload-release-asset@v1
